### ISSUE TITLE
CW 1.0, User inputs must be deserialized into String, not Addr.

### ISSUE THREAD

**Issue by denismaxim0v** [scrtlabs/snip20-reference-impl#33]
Currently [this branch](https://github.com/scrtlabs/snip20-reference-impl/tree/cosmwasm-v1) has the updated code that ports the implementation to cosmwasm 1.0, however the changes made seem to be wrong. Cosmwasm docs state:  
> The new type Addr was created to hold validated addresses. Those can be created via Addr::unchecked, Api::addr_validate, Api::addr_humanize and JSON deserialization. In order to maintain type safety, deserialization into Addr must only be done from trusted sources like a contract's state or a query response. User inputs must be deserialized into String.

> `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.

User inputs such as
```rust
TransferFrom {
        owner: Addr,
        recipient: Addr,
        amount: Uint128,
        memo: Option<String>,
        padding: Option<String>,
}
```
Should deserialize into strings instead of Addr and then validated using `addr_validate`. Please refer to the original cw20 implementation [here](https://github.com/CosmWasm/cw-plus/blob/24af1b9bff0fb4dcd5592fdd546dd56d135ad52a/packages/cw20/src/msg.rs)
```rust
 TransferFrom {
        owner: String,
        recipient: String,
        amount: Uint128,
},
```

**Comment by toml01** [comment]
Thanks @denismaxim0v you are correct.
Keep in mind that the V1 version of snip20 implementation is still WIP, so use at your own risk

cc @eladr7

**Comment by eladr7** [comment]
Thank you Denis.
I updated the PR accordingly.
