### ISSUE TITLE
SNIP-25 allowance queries allow anyone to query by signing a permit.

### ISSUE THREAD

**Issue by aakamenov** [scrtlabs/snip20-reference-impl#80]
The new `AllowancesGiven` and `AllowancesReceived` queries added in #77 make it possible for anyone to successfully pass authentication with a permit to view other addresses allowances. I've made a demo using `secretjs` to better illustrate this.

Here we have `secret1v6xp4qnlt79grjnf9rhrx9nke34k4pq04lcglm` send a `200000000` allowance to `secret1f2mf5xusm28a2pvzu5ztu58c5w89kdqjcy4sfw`. With each run of the script we generate a random address and sign a permit with it but we are able to view their allowances just the same. I built and uploaded the contract using the latest commit on `master` -  81ad971

```typescript
import { Wallet, SecretNetworkClient } from 'secretjs'

async function permit_test() {
    const code_id = 20597
    const contract_address = 'secret1stn58qtmk64jvuk8u33fqdngad90djx7ycs82s'
    const code_hash = '4e53e1d9d87241e58d16137b7056b14fe361b37a39ab074120912f6361184f02'

    const wallet = new Wallet()
    const client = new SecretNetworkClient({
        wallet,
        walletAddress: wallet.address,
        chainId: 'pulsar-2',
        url: 'https://api.pulsar.scrttestnet.com'
    })

    const permit = await client.utils.accessControl.permit.sign(
        wallet.address,
        'pulsar-2',
        'allowance test',
        [contract_address],
        ['allowance'],
        false
    )

    let resp = await client.query.compute.queryContract({
        contract_address,
        code_hash,
        query: { with_permit: {
            permit,
            query: { allowances_given: {
                owner: 'secret1v6xp4qnlt79grjnf9rhrx9nke34k4pq04lcglm',
                page_size: 10
            } }
        } }
    })

    console.log(JSON.stringify(resp, null, 2))

    resp = await client.query.compute.queryContract({
        contract_address,
        code_hash,
        query: { with_permit: {
            permit,
            query: { allowances_received: {
                spender: 'secret1f2mf5xusm28a2pvzu5ztu58c5w89kdqjcy4sfw',
                page_size: 10
            } }
        } }
    })

    console.log(JSON.stringify(resp, null, 2))
}

permit_test().catch(console.log)
```
The fix should be to simply check whether the validated address from the permit is the `owner` or `spender` field respectively?
But in that case those fields become redundant so they should be removed.

Also there is this comment which from what I can gather says that we should avoid canonicalizing or validating the address using `api.deps` so it should not have any bearing on the issue, correct?
https://github.com/scrtlabs/snip20-reference-impl/blob/81ad9714e50b890a50d8394dcac718950da127b6/src/contract.rs#L964-L967

Maybe @darwinzer0 can provide more insight into this?

**Comment by mradkov** [comment]
⌛

**Comment by Cashmaney** [comment]
Thanks for reporting this! You're 100% right, there's a missing check there for spender/owner. I'll also advise any devs who might have deployed contracts from this version to look out of the issue.

I added this as a fix for the issue https://github.com/scrtlabs/snip20-reference-impl/pull/84 - I wanted to avoid changing interfaces, even though the owner/spender params could be omitted, breaking interfaces which apps may rely on is never fun.

**Comment by aakamenov** [comment]
Great! The fix looks good to me. I checked all the contracts uploaded mainnet and there are currently 0 instances uploaded that use the code at that commit (which is still the latest on `master`). Of course, that doesn't disqualify the possibility that someone could've forked and changed the code which would result in a different code hash. But it seems to me that now is the time to change the interface, as otherwise, it will remain misleading. If I not mistaken the SNIP-25 standard isn't even official yet?

**Comment by mradkov** [comment]
> Great! The fix looks good to me. I checked all the contracts uploaded to mainnet and there are currently 0 instances uploaded that use the code at that commit (which is still the latest on `master`). Of course, that doesn't disqualify the possibility that someone could've forked and changed the code which would result in a different code hash. But it seems to me that now is the time to change the interface, as otherwise, it will remain misleading. If I not mistaken the SNIP-25 standard isn't even official yet?

I think there should be some tokens which use SNIP-25 already as Shade has launched their migration tool weeks ago. (https://blog.shadeprotocol.io/snip-token-migration-launching/)

> SHD
> IST
> USK
> KUJI
> ATOM
> JUNO
> OSMO
> stJUNO
> stATOM
> stOSMO
> STRIDE
> BLD
> LUNA

**Comment by darwinzer0** [comment]
thanks for catching this @aakamenov and fixing it @Cashmaney! sorry I didn't notice this issue earlier.

**Comment by darwinzer0** [comment]
> > Great! The fix looks good to me. I checked all the contracts uploaded to mainnet and there are currently 0 instances uploaded that use the code at that commit (which is still the latest on `master`). Of course, that doesn't disqualify the possibility that someone could've forked and changed the code which would result in a different code hash. But it seems to me that now is the time to change the interface, as otherwise, it will remain misleading. If I not mistaken the SNIP-25 standard isn't even official yet?
> 
> I think there should be some tokens which use SNIP-25 already as Shade has launched their migration tool weeks ago. (https://blog.shadeprotocol.io/snip-token-migration-launching/)
> 
> > SHD
> > IST
> > USK
> > KUJI
> > ATOM
> > JUNO
> > OSMO
> > stJUNO
> > stATOM
> > stOSMO
> > STRIDE
> > BLD
> > LUNA

I don't think this was ever planned to be part of SNIP-25. It will probably go in as SNIP-26.

**Comment by darwinzer0** [comment]
hmmm, it does look the queries were implemented in the Shade SNIP-25s. You can tell by sending an incorrect message type and parsing the error message. 

Not that it would necessarily have meant catching this bug, but I think it would be a good idea to keep updates like this in a separate branch from master until the SNIPs are officially written-up (same for the other SNIP-25 changes). Either that or keep separate branches for each new SNIP iteration.

**Comment by Cashmaney** [comment]
Yeah, everyone was rushing to make sure new tokens fix previous issues and have as much functionality as possible which always adds some risk. In the future we def need to make sure to keep new features standardized.

Also merged the changes from the PR. I'm going to keep the interfaces as-is for now - we can make the owner parameter optional later, but if we want to do that, we should make sure that the regular allowance queries reflect that and that the toolkit/secretjs etc all gets updated to reflect those changes.
